# Default values for templateExample.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sample
  tag: v0.1.0
  pullPolicy: Always

service:
  name: Node
  type: NodePort
  servicePort: 5000

resources:
  cpu: 100m
  memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
