kind: Deployment
apiVersion: apps/v1
metadata:
  name: pythonserver
  labels:
    app: pythonserver-cooper
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonserver
      scope: cooper
      env: dev
  template:
    metadata:
      labels:
        app: pythonserver
        scope: cooper
        env: dev
    spec:
      #securityContext:
        #runAsUser: 1000
        #runAsGroup: 1000
      containers:
      - name: pythonserver
        image: "ubaldopuocci/mypythonserver"
        imagePullPolicy: Always
        resources: 
          limits: 
            memory: 500Mi
            cpu: 500m
        volumeMounts:
          - name:  config-vol
            mountPath:  /tmp
          - name: config-pv
            mountPath: /temp
        env:
        - name: ENVKEY
          value: test4kube
        - name: MYSQL_HOST
          value: mysql-cooper
        - name: MYSQL_PORT
          value: "3306"
      volumes:
       - name: config-vol
         configMap:
           name: config
       - name: config-pv
         persistentVolumeClaim:
           claimName: config-pvc