kind: PersistentVolume
apiVersion: v1
metadata:
  name: config-pv
  labels:
    type: local-pv
spec:
  storageClassName: manual
  capacity:
    storage: 15Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/skytap/storage/config"