kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-pvc
  labels:
    type: project-cooper
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi