kind: Service
apiVersion: v1
metadata:
  name: pythonserver-service
  labels:
    app: pythonserver-cooper
    env: dev
spec:
  selector:
    app: pythonserver
    scope: cooper
    env: dev
  type: NodePort
  ports:
    - name: http
      protocol: "TCP"
      port: 8082      
      nodePort: 31119